<a href="https://colab.research.google.com/github/YushirohMurasakih/Linear-Algebra/blob/main/Arevalo_Lab8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Laboratory Activity 8 \\
Arevalo, John Harold G.

1.  Try to find your own example of a system of linear equations (minimum of 2 equations) and solve them using the inverse equation. Explain the details of your example.

$$
Matrices = \left\{
    \begin{array}\\
        2x+y+z=8\\ 
        5x -3y +2z=3 \\
        7x + y +3z=20
    \end{array}
\right. $$

$$
\begin{bmatrix}2&1&1\\5&-3&2\\7&1&3\end{bmatrix} \cdot \begin{bmatrix}x\\ y\\z\end{bmatrix} = \begin{bmatrix}8\\3\\20\end{bmatrix}
$$

In [9]:
import numpy as np

In [10]:
A = np.array([
              [2,1,1],
              [5,-3,2],
              [7,1,3]
])

B = np.array([
              [8],
              [3],
              [20]
])

In [11]:
print("A = \n", A)
print("\nB = \n", B)

A = 
 [[ 2  1  1]
 [ 5 -3  2]
 [ 7  1  3]]

B = 
 [[ 8]
 [ 3]
 [20]]


In [13]:
x_y = np.linalg.solve(A, B)

print(x_y)

[[2.]
 [3.]
 [1.]]


In [14]:
ans1 = A @ Xinv_Y
np.allclose(ans1, B)

True

$$
Matrices = \left\{
    \begin{array}\\
        3a-b+14c=7\\ 
        2a +2b +3c=0 \\
        a - 12b -18c=33
    \end{array}
\right. $$

$$
\begin{bmatrix}3&-1&14\\2&2&3\\a&-12&-18\end{bmatrix} \cdot \begin{bmatrix}a\\ b\\c\end{bmatrix} = \begin{bmatrix}7\\0\\33\end{bmatrix}
$$

In [7]:
C = np.array([
              [3,-1,14],
              [2,2,3],
              [1,-12,-18]
])

D = np.array([
              [7],
              [0],
              [33]
])

In [8]:
print("C = \n", C)
print("\nD = \n", D)

C = 
 [[  3  -1  14]
 [  2   2   3]
 [  1 -12 -18]]

D = 
 [[ 7]
 [ 0]
 [33]]


In [16]:
x_y = np.linalg.solve(C, D)

print(x_y)

[[ 2.53846154]
 [-2.23325062]
 [-0.20347395]]


In [18]:
ans1 = C @ Xinv_Y
np.allclose(ans1, D)

True

2. Using your example in (1) solve it using np.linalg.solve(). Explain the function and its difference using the inverse equation.

In [19]:
X_inv = np.linalg.inv(A)
Xinv_Y = X_inv @ B

print(Xinv_Y)

[[2.]
 [3.]
 [1.]]


In [20]:
X_inv = np.linalg.inv(C)
Xinv_Y = X_inv @ D

print(Xinv_Y)

[[ 2.53846154]
 [-2.23325062]
 [-0.20347395]]
